name = "AIHydroPoints"
uuid = "108bb8f1-8e88-4b63-a044-74d4b42570d0"
authors = ["robot144 <robot144@protonmail.com>"]
version = "0.1.0"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Minio = "4281f0d9-7ae0-406e-9172-b7277c1efa20"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
ZarrDatasets = "519a4cdf-1362-424a-9ea1-b1d782dbb24b"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
AWS = "1.92.0"
BSON = "0.3.9"
CSV = "0.10.15"
CUDA = "5.7.0"
DataFrames = "1.7.0"
Dates = "1.11.0"
FFTW = "1.8.1"
Flux = "0.16.3"
HTTP = "1.10.17"
JLD2 = "0.5.11"
Minio = "0.2.2"
NCDatasets = "0.14.6"
NetCDF = "0.12.2"
Plots = "1.40.9"
Printf = "1.11.0"
ProgressMeter = "1.10.2"
Rasters = "0.14.2"
Revise = "3.8.0"
Statistics = "1.11.1"
TOML = "1.0.3"
Test = "1.11.0"
URIs = "1.6.1"
ZarrDatasets = "0.1.2"
cuDNN = "1.4.2"
